# Generated by Django 4.2.16 on 2024-09-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_subtitle_post_edit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edit_date',
            field=models.CharField(max_length=200),
        ),
    ]
